Repository jenkinsci/github-scm-trait-notification-context-plugin, pull requests merged in 2023-09, with the labels that each got.

#9 Enable CD
  .github/dependabot.yml
  .github/workflows/cd.yaml
  .mvn/maven.config
  pom.xml
Labels: internal

#3 Use proper case for GitHub
  README.md
  pom.xml
  src/main/java/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait.java
  src/main/resources/index.jelly
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/help-contextLabel.html
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/help.html
Labels: fix

#10 Migrate plugin doc to Github
  pom.xml
Labels: internal, fix

#7 Support multiple notifications
  pom.xml
  src/main/java/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait.java
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/config.jelly
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/help-contextLabel.html
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/help-multipleStatusDelimiter.html
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/help-multipleStatuses.html
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/help-typeSuffix.html
  src/main/resources/org/jenkinsci/plugins/githubScmTraitNotificationContext/NotificationContextTrait/help.html
Labels: enhancement
